# Generated by Django 4.1.3 on 2022-11-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body_count', models.FloatField()),
                ('fig_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
